import './main.js/firebase';
import './main.js/location';
import './main.js/google-translate';
import './main.js/render-favorites-movie';
import './main.js/fetch-class';
import './main.js/scroll-up-btn';
import './main.js/switcher';
import './main.js/hidden-footer';
import './main.js/preloader';
// import './main.js/canvas';
import './main.js/team-modal';
import './main.js/modal-queue-library';
import './main.js/modal-watched-library';
